name: Gradle build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle stuff
        uses: actions/cache@v3
        with:
          key: gradle-${{ hashFiles('*.gradle.kts', 'gradle.properties', '*/*.gradle.kts', 'gradle/**') }}
          restore-keys: gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Test
        run: echo $ACTIONS_CACHE_URL
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs
